### ISSUE TITLE
TypeError: Shiny.setInputValue is not a function

### ISSUE THREAD

**Issue by ivokwee** [bigomics/bigdash#13]
The JS console gives a  "TypeError: Shiny.setInputValue is not a function". See below. Not sure if this affects functioning.

![image](https://user-images.githubusercontent.com/19613146/224834345-c049adb1-b401-4ccd-ba69-c876deccd0a4.png)

**Comment by JohnCoene** [comment]
It does not, event fires before Shiny connects. Can be ignored.

**Comment by ivokwee** [comment]
ok
