### ISSUE TITLE
feature request: add dark mode or other themes

### ISSUE THREAD

**Issue by ncullen93** [bigomics/bigdash#16]
Adding a dark mode or other themes to bigdash would be a significant enhancement. The way I have seen this done is to have the theme be a css class at the overall page level, like whatever the most outer div is.

**Comment by ivokwee** [comment]
Bslib has great theming support which trickles down to plotly/ggplot and even base plots. Would love to see a dark mode. I think bigdash itself is using bslib theming, so it should be "easy". See here https://rstudio.github.io/bslib/articles/bslib.html#custom
